name: atelierlaurier

type: python

up:
  - python: 3.6.5
  - pip: requirements.txt
  - python_develop
  - node:
      yarn: false
      version: 8.11.3
commands:
  webpack:
    desc: "Update and compile js dependencies"
    run: ./node_modules/.bin/webpack
  server:
    desc: "Run the development server"
    run: pserve development.ini
  test:
    desc: "run tests"
    run: pytest
  minor:
    desc: "Bump to next minor version"
    run: bumpversion minor
  major:
    desc: "Bump to the next major version"
    run: bumpversion major
